name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'etl_processing/lambda/**'
      - 'deployment/ci_cd/github_actions/deploy_lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        cd etl_processing/lambda
        pip install -r requirements.txt -t .

    - name: Package Lambda function
      run: |
        cd etl_processing/lambda
        zip -r lambda_function.zip .

    - name: Deploy Lambda function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
      run: |
        aws lambda update-function-code --function-name start-glue-job --zip-file fileb://etl_processing/lambda/lambda_function.zip
